/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout/route'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as PathlessLayoutIndexImport } from './routes/_pathlessLayout/index'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as DashboardImagesImport } from './routes/dashboard/images'
import { Route as DashboardImagesIndexImport } from './routes/dashboard/images/index'
import { Route as DashboardGuidesIndexImport } from './routes/dashboard/guides/index'
import { Route as PathlessLayoutProductReviewsIndexImport } from './routes/_pathlessLayout/product-reviews/index'
import { Route as PathlessLayoutGuidesIndexImport } from './routes/_pathlessLayout/guides/index'
import { Route as PathlessLayoutCalculatorsIndexImport } from './routes/_pathlessLayout/calculators/index'
import { Route as PathlessLayoutBlogsIndexImport } from './routes/_pathlessLayout/blogs/index'
import { Route as PathlessLayoutProductReviewsReviewIdImport } from './routes/_pathlessLayout/product-reviews/$reviewId'
import { Route as PathlessLayoutBlogsIdImport } from './routes/_pathlessLayout/blogs/$id'
import { Route as PathlessLayoutGuidesCategoryIndexImport } from './routes/_pathlessLayout/guides/$category/index'
import { Route as PathlessLayoutCalculatorsSolarSystemIndexImport } from './routes/_pathlessLayout/calculators/solar-system/index'
import { Route as PathlessLayoutCalculatorsHomeLoadIndexImport } from './routes/_pathlessLayout/calculators/home-load/index'
import { Route as PathlessLayoutGuidesCategorySlugImport } from './routes/_pathlessLayout/guides/$category/$slug'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutRouteRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const PathlessLayoutIndexRoute = PathlessLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardImagesRoute = DashboardImagesImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardImagesIndexRoute = DashboardImagesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardImagesRoute,
} as any)

const DashboardGuidesIndexRoute = DashboardGuidesIndexImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const PathlessLayoutProductReviewsIndexRoute =
  PathlessLayoutProductReviewsIndexImport.update({
    id: '/product-reviews/',
    path: '/product-reviews/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutGuidesIndexRoute = PathlessLayoutGuidesIndexImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutCalculatorsIndexRoute =
  PathlessLayoutCalculatorsIndexImport.update({
    id: '/calculators/',
    path: '/calculators/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutBlogsIndexRoute = PathlessLayoutBlogsIndexImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutProductReviewsReviewIdRoute =
  PathlessLayoutProductReviewsReviewIdImport.update({
    id: '/product-reviews/$reviewId',
    path: '/product-reviews/$reviewId',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutBlogsIdRoute = PathlessLayoutBlogsIdImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutGuidesCategoryIndexRoute =
  PathlessLayoutGuidesCategoryIndexImport.update({
    id: '/guides/$category/',
    path: '/guides/$category/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutCalculatorsSolarSystemIndexRoute =
  PathlessLayoutCalculatorsSolarSystemIndexImport.update({
    id: '/calculators/solar-system/',
    path: '/calculators/solar-system/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutCalculatorsHomeLoadIndexRoute =
  PathlessLayoutCalculatorsHomeLoadIndexImport.update({
    id: '/calculators/home-load/',
    path: '/calculators/home-load/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutGuidesCategorySlugRoute =
  PathlessLayoutGuidesCategorySlugImport.update({
    id: '/guides/$category/$slug',
    path: '/guides/$category/$slug',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/images': {
      id: '/dashboard/images'
      path: '/images'
      fullPath: '/dashboard/images'
      preLoaderRoute: typeof DashboardImagesImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_pathlessLayout/blogs/$id': {
      id: '/_pathlessLayout/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof PathlessLayoutBlogsIdImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/product-reviews/$reviewId': {
      id: '/_pathlessLayout/product-reviews/$reviewId'
      path: '/product-reviews/$reviewId'
      fullPath: '/product-reviews/$reviewId'
      preLoaderRoute: typeof PathlessLayoutProductReviewsReviewIdImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/blogs/': {
      id: '/_pathlessLayout/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof PathlessLayoutBlogsIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/calculators/': {
      id: '/_pathlessLayout/calculators/'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof PathlessLayoutCalculatorsIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/guides/': {
      id: '/_pathlessLayout/guides/'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof PathlessLayoutGuidesIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/product-reviews/': {
      id: '/_pathlessLayout/product-reviews/'
      path: '/product-reviews'
      fullPath: '/product-reviews'
      preLoaderRoute: typeof PathlessLayoutProductReviewsIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/dashboard/guides/': {
      id: '/dashboard/guides/'
      path: '/guides'
      fullPath: '/dashboard/guides'
      preLoaderRoute: typeof DashboardGuidesIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/images/': {
      id: '/dashboard/images/'
      path: '/'
      fullPath: '/dashboard/images/'
      preLoaderRoute: typeof DashboardImagesIndexImport
      parentRoute: typeof DashboardImagesImport
    }
    '/_pathlessLayout/guides/$category/$slug': {
      id: '/_pathlessLayout/guides/$category/$slug'
      path: '/guides/$category/$slug'
      fullPath: '/guides/$category/$slug'
      preLoaderRoute: typeof PathlessLayoutGuidesCategorySlugImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/calculators/home-load/': {
      id: '/_pathlessLayout/calculators/home-load/'
      path: '/calculators/home-load'
      fullPath: '/calculators/home-load'
      preLoaderRoute: typeof PathlessLayoutCalculatorsHomeLoadIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/calculators/solar-system/': {
      id: '/_pathlessLayout/calculators/solar-system/'
      path: '/calculators/solar-system'
      fullPath: '/calculators/solar-system'
      preLoaderRoute: typeof PathlessLayoutCalculatorsSolarSystemIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/guides/$category/': {
      id: '/_pathlessLayout/guides/$category/'
      path: '/guides/$category'
      fullPath: '/guides/$category'
      preLoaderRoute: typeof PathlessLayoutGuidesCategoryIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutBlogsIdRoute: typeof PathlessLayoutBlogsIdRoute
  PathlessLayoutProductReviewsReviewIdRoute: typeof PathlessLayoutProductReviewsReviewIdRoute
  PathlessLayoutBlogsIndexRoute: typeof PathlessLayoutBlogsIndexRoute
  PathlessLayoutCalculatorsIndexRoute: typeof PathlessLayoutCalculatorsIndexRoute
  PathlessLayoutGuidesIndexRoute: typeof PathlessLayoutGuidesIndexRoute
  PathlessLayoutProductReviewsIndexRoute: typeof PathlessLayoutProductReviewsIndexRoute
  PathlessLayoutGuidesCategorySlugRoute: typeof PathlessLayoutGuidesCategorySlugRoute
  PathlessLayoutCalculatorsHomeLoadIndexRoute: typeof PathlessLayoutCalculatorsHomeLoadIndexRoute
  PathlessLayoutCalculatorsSolarSystemIndexRoute: typeof PathlessLayoutCalculatorsSolarSystemIndexRoute
  PathlessLayoutGuidesCategoryIndexRoute: typeof PathlessLayoutGuidesCategoryIndexRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutBlogsIdRoute: PathlessLayoutBlogsIdRoute,
  PathlessLayoutProductReviewsReviewIdRoute:
    PathlessLayoutProductReviewsReviewIdRoute,
  PathlessLayoutBlogsIndexRoute: PathlessLayoutBlogsIndexRoute,
  PathlessLayoutCalculatorsIndexRoute: PathlessLayoutCalculatorsIndexRoute,
  PathlessLayoutGuidesIndexRoute: PathlessLayoutGuidesIndexRoute,
  PathlessLayoutProductReviewsIndexRoute:
    PathlessLayoutProductReviewsIndexRoute,
  PathlessLayoutGuidesCategorySlugRoute: PathlessLayoutGuidesCategorySlugRoute,
  PathlessLayoutCalculatorsHomeLoadIndexRoute:
    PathlessLayoutCalculatorsHomeLoadIndexRoute,
  PathlessLayoutCalculatorsSolarSystemIndexRoute:
    PathlessLayoutCalculatorsSolarSystemIndexRoute,
  PathlessLayoutGuidesCategoryIndexRoute:
    PathlessLayoutGuidesCategoryIndexRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

interface DashboardImagesRouteChildren {
  DashboardImagesIndexRoute: typeof DashboardImagesIndexRoute
}

const DashboardImagesRouteChildren: DashboardImagesRouteChildren = {
  DashboardImagesIndexRoute: DashboardImagesIndexRoute,
}

const DashboardImagesRouteWithChildren = DashboardImagesRoute._addFileChildren(
  DashboardImagesRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardImagesRoute: typeof DashboardImagesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGuidesIndexRoute: typeof DashboardGuidesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardImagesRoute: DashboardImagesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGuidesIndexRoute: DashboardGuidesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PathlessLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/images': typeof DashboardImagesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof PathlessLayoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/blogs/$id': typeof PathlessLayoutBlogsIdRoute
  '/product-reviews/$reviewId': typeof PathlessLayoutProductReviewsReviewIdRoute
  '/blogs': typeof PathlessLayoutBlogsIndexRoute
  '/calculators': typeof PathlessLayoutCalculatorsIndexRoute
  '/guides': typeof PathlessLayoutGuidesIndexRoute
  '/product-reviews': typeof PathlessLayoutProductReviewsIndexRoute
  '/dashboard/guides': typeof DashboardGuidesIndexRoute
  '/dashboard/images/': typeof DashboardImagesIndexRoute
  '/guides/$category/$slug': typeof PathlessLayoutGuidesCategorySlugRoute
  '/calculators/home-load': typeof PathlessLayoutCalculatorsHomeLoadIndexRoute
  '/calculators/solar-system': typeof PathlessLayoutCalculatorsSolarSystemIndexRoute
  '/guides/$category': typeof PathlessLayoutGuidesCategoryIndexRoute
}

export interface FileRoutesByTo {
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof PathlessLayoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/blogs/$id': typeof PathlessLayoutBlogsIdRoute
  '/product-reviews/$reviewId': typeof PathlessLayoutProductReviewsReviewIdRoute
  '/blogs': typeof PathlessLayoutBlogsIndexRoute
  '/calculators': typeof PathlessLayoutCalculatorsIndexRoute
  '/guides': typeof PathlessLayoutGuidesIndexRoute
  '/product-reviews': typeof PathlessLayoutProductReviewsIndexRoute
  '/dashboard/guides': typeof DashboardGuidesIndexRoute
  '/dashboard/images': typeof DashboardImagesIndexRoute
  '/guides/$category/$slug': typeof PathlessLayoutGuidesCategorySlugRoute
  '/calculators/home-load': typeof PathlessLayoutCalculatorsHomeLoadIndexRoute
  '/calculators/solar-system': typeof PathlessLayoutCalculatorsSolarSystemIndexRoute
  '/guides/$category': typeof PathlessLayoutGuidesCategoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/images': typeof DashboardImagesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_pathlessLayout/blogs/$id': typeof PathlessLayoutBlogsIdRoute
  '/_pathlessLayout/product-reviews/$reviewId': typeof PathlessLayoutProductReviewsReviewIdRoute
  '/_pathlessLayout/blogs/': typeof PathlessLayoutBlogsIndexRoute
  '/_pathlessLayout/calculators/': typeof PathlessLayoutCalculatorsIndexRoute
  '/_pathlessLayout/guides/': typeof PathlessLayoutGuidesIndexRoute
  '/_pathlessLayout/product-reviews/': typeof PathlessLayoutProductReviewsIndexRoute
  '/dashboard/guides/': typeof DashboardGuidesIndexRoute
  '/dashboard/images/': typeof DashboardImagesIndexRoute
  '/_pathlessLayout/guides/$category/$slug': typeof PathlessLayoutGuidesCategorySlugRoute
  '/_pathlessLayout/calculators/home-load/': typeof PathlessLayoutCalculatorsHomeLoadIndexRoute
  '/_pathlessLayout/calculators/solar-system/': typeof PathlessLayoutCalculatorsSolarSystemIndexRoute
  '/_pathlessLayout/guides/$category/': typeof PathlessLayoutGuidesCategoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/dashboard/images'
    | '/dashboard/settings'
    | '/'
    | '/dashboard/'
    | '/blogs/$id'
    | '/product-reviews/$reviewId'
    | '/blogs'
    | '/calculators'
    | '/guides'
    | '/product-reviews'
    | '/dashboard/guides'
    | '/dashboard/images/'
    | '/guides/$category/$slug'
    | '/calculators/home-load'
    | '/calculators/solar-system'
    | '/guides/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard/settings'
    | '/'
    | '/dashboard'
    | '/blogs/$id'
    | '/product-reviews/$reviewId'
    | '/blogs'
    | '/calculators'
    | '/guides'
    | '/product-reviews'
    | '/dashboard/guides'
    | '/dashboard/images'
    | '/guides/$category/$slug'
    | '/calculators/home-load'
    | '/calculators/solar-system'
    | '/guides/$category'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/dashboard'
    | '/dashboard/images'
    | '/dashboard/settings'
    | '/_pathlessLayout/'
    | '/dashboard/'
    | '/_pathlessLayout/blogs/$id'
    | '/_pathlessLayout/product-reviews/$reviewId'
    | '/_pathlessLayout/blogs/'
    | '/_pathlessLayout/calculators/'
    | '/_pathlessLayout/guides/'
    | '/_pathlessLayout/product-reviews/'
    | '/dashboard/guides/'
    | '/dashboard/images/'
    | '/_pathlessLayout/guides/$category/$slug'
    | '/_pathlessLayout/calculators/home-load/'
    | '/_pathlessLayout/calculators/solar-system/'
    | '/_pathlessLayout/guides/$category/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_pathlessLayout",
        "/dashboard"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout/route.tsx",
      "children": [
        "/_pathlessLayout/",
        "/_pathlessLayout/blogs/$id",
        "/_pathlessLayout/product-reviews/$reviewId",
        "/_pathlessLayout/blogs/",
        "/_pathlessLayout/calculators/",
        "/_pathlessLayout/guides/",
        "/_pathlessLayout/product-reviews/",
        "/_pathlessLayout/guides/$category/$slug",
        "/_pathlessLayout/calculators/home-load/",
        "/_pathlessLayout/calculators/solar-system/",
        "/_pathlessLayout/guides/$category/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/images",
        "/dashboard/settings",
        "/dashboard/",
        "/dashboard/guides/"
      ]
    },
    "/dashboard/images": {
      "filePath": "dashboard/images.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/images/"
      ]
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/_pathlessLayout/": {
      "filePath": "_pathlessLayout/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/_pathlessLayout/blogs/$id": {
      "filePath": "_pathlessLayout/blogs/$id.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/product-reviews/$reviewId": {
      "filePath": "_pathlessLayout/product-reviews/$reviewId.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/blogs/": {
      "filePath": "_pathlessLayout/blogs/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/calculators/": {
      "filePath": "_pathlessLayout/calculators/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/guides/": {
      "filePath": "_pathlessLayout/guides/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/product-reviews/": {
      "filePath": "_pathlessLayout/product-reviews/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/dashboard/guides/": {
      "filePath": "dashboard/guides/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/images/": {
      "filePath": "dashboard/images/index.tsx",
      "parent": "/dashboard/images"
    },
    "/_pathlessLayout/guides/$category/$slug": {
      "filePath": "_pathlessLayout/guides/$category/$slug.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/calculators/home-load/": {
      "filePath": "_pathlessLayout/calculators/home-load/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/calculators/solar-system/": {
      "filePath": "_pathlessLayout/calculators/solar-system/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/guides/$category/": {
      "filePath": "_pathlessLayout/guides/$category/index.tsx",
      "parent": "/_pathlessLayout"
    }
  }
}
ROUTE_MANIFEST_END */
