/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PathlessLayoutImport } from './routes/_pathlessLayout'
import { Route as IndexImport } from './routes/index'
import { Route as GuidesIndexImport } from './routes/guides/index'
import { Route as CalculatorsIndexImport } from './routes/calculators/index'
import { Route as BlogsIndexImport } from './routes/blogs/index'
import { Route as BlogsIdImport } from './routes/blogs/$id'
import { Route as GuidesCategoryIndexImport } from './routes/guides/$category/index'
import { Route as CalculatorsSolarSystemIndexImport } from './routes/calculators/solar-system/index'
import { Route as CalculatorsHomeLoadIndexImport } from './routes/calculators/home-load/index'
import { Route as GuidesCategorySlugImport } from './routes/guides/$category/$slug'

// Create/Update Routes

const PathlessLayoutRoute = PathlessLayoutImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GuidesIndexRoute = GuidesIndexImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRoute,
} as any)

const CalculatorsIndexRoute = CalculatorsIndexImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRoute,
} as any)

const BlogsIndexRoute = BlogsIndexImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRoute,
} as any)

const BlogsIdRoute = BlogsIdImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => rootRoute,
} as any)

const GuidesCategoryIndexRoute = GuidesCategoryIndexImport.update({
  id: '/guides/$category/',
  path: '/guides/$category/',
  getParentRoute: () => rootRoute,
} as any)

const CalculatorsSolarSystemIndexRoute =
  CalculatorsSolarSystemIndexImport.update({
    id: '/calculators/solar-system/',
    path: '/calculators/solar-system/',
    getParentRoute: () => rootRoute,
  } as any)

const CalculatorsHomeLoadIndexRoute = CalculatorsHomeLoadIndexImport.update({
  id: '/calculators/home-load/',
  path: '/calculators/home-load/',
  getParentRoute: () => rootRoute,
} as any)

const GuidesCategorySlugRoute = GuidesCategorySlugImport.update({
  id: '/guides/$category/$slug',
  path: '/guides/$category/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutImport
      parentRoute: typeof rootRoute
    }
    '/blogs/$id': {
      id: '/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof BlogsIdImport
      parentRoute: typeof rootRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexImport
      parentRoute: typeof rootRoute
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsIndexImport
      parentRoute: typeof rootRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesIndexImport
      parentRoute: typeof rootRoute
    }
    '/guides/$category/$slug': {
      id: '/guides/$category/$slug'
      path: '/guides/$category/$slug'
      fullPath: '/guides/$category/$slug'
      preLoaderRoute: typeof GuidesCategorySlugImport
      parentRoute: typeof rootRoute
    }
    '/calculators/home-load/': {
      id: '/calculators/home-load/'
      path: '/calculators/home-load'
      fullPath: '/calculators/home-load'
      preLoaderRoute: typeof CalculatorsHomeLoadIndexImport
      parentRoute: typeof rootRoute
    }
    '/calculators/solar-system/': {
      id: '/calculators/solar-system/'
      path: '/calculators/solar-system'
      fullPath: '/calculators/solar-system'
      preLoaderRoute: typeof CalculatorsSolarSystemIndexImport
      parentRoute: typeof rootRoute
    }
    '/guides/$category/': {
      id: '/guides/$category/'
      path: '/guides/$category'
      fullPath: '/guides/$category'
      preLoaderRoute: typeof GuidesCategoryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PathlessLayoutRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/blogs': typeof BlogsIndexRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/guides/$category/$slug': typeof GuidesCategorySlugRoute
  '/calculators/home-load': typeof CalculatorsHomeLoadIndexRoute
  '/calculators/solar-system': typeof CalculatorsSolarSystemIndexRoute
  '/guides/$category': typeof GuidesCategoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PathlessLayoutRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/blogs': typeof BlogsIndexRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/guides/$category/$slug': typeof GuidesCategorySlugRoute
  '/calculators/home-load': typeof CalculatorsHomeLoadIndexRoute
  '/calculators/solar-system': typeof CalculatorsSolarSystemIndexRoute
  '/guides/$category': typeof GuidesCategoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/blogs/': typeof BlogsIndexRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/guides/$category/$slug': typeof GuidesCategorySlugRoute
  '/calculators/home-load/': typeof CalculatorsHomeLoadIndexRoute
  '/calculators/solar-system/': typeof CalculatorsSolarSystemIndexRoute
  '/guides/$category/': typeof GuidesCategoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/blogs/$id'
    | '/blogs'
    | '/calculators'
    | '/guides'
    | '/guides/$category/$slug'
    | '/calculators/home-load'
    | '/calculators/solar-system'
    | '/guides/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/blogs/$id'
    | '/blogs'
    | '/calculators'
    | '/guides'
    | '/guides/$category/$slug'
    | '/calculators/home-load'
    | '/calculators/solar-system'
    | '/guides/$category'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/blogs/$id'
    | '/blogs/'
    | '/calculators/'
    | '/guides/'
    | '/guides/$category/$slug'
    | '/calculators/home-load/'
    | '/calculators/solar-system/'
    | '/guides/$category/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRoute
  BlogsIdRoute: typeof BlogsIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  GuidesCategorySlugRoute: typeof GuidesCategorySlugRoute
  CalculatorsHomeLoadIndexRoute: typeof CalculatorsHomeLoadIndexRoute
  CalculatorsSolarSystemIndexRoute: typeof CalculatorsSolarSystemIndexRoute
  GuidesCategoryIndexRoute: typeof GuidesCategoryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRoute,
  BlogsIdRoute: BlogsIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  GuidesCategorySlugRoute: GuidesCategorySlugRoute,
  CalculatorsHomeLoadIndexRoute: CalculatorsHomeLoadIndexRoute,
  CalculatorsSolarSystemIndexRoute: CalculatorsSolarSystemIndexRoute,
  GuidesCategoryIndexRoute: GuidesCategoryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_pathlessLayout",
        "/blogs/$id",
        "/blogs/",
        "/calculators/",
        "/guides/",
        "/guides/$category/$slug",
        "/calculators/home-load/",
        "/calculators/solar-system/",
        "/guides/$category/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout.tsx"
    },
    "/blogs/$id": {
      "filePath": "blogs/$id.tsx"
    },
    "/blogs/": {
      "filePath": "blogs/index.tsx"
    },
    "/calculators/": {
      "filePath": "calculators/index.tsx"
    },
    "/guides/": {
      "filePath": "guides/index.tsx"
    },
    "/guides/$category/$slug": {
      "filePath": "guides/$category/$slug.tsx"
    },
    "/calculators/home-load/": {
      "filePath": "calculators/home-load/index.tsx"
    },
    "/calculators/solar-system/": {
      "filePath": "calculators/solar-system/index.tsx"
    },
    "/guides/$category/": {
      "filePath": "guides/$category/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
