/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout/route'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as PathlessLayoutIndexImport } from './routes/_pathlessLayout/index'
import { Route as DashboardSettingsIndexImport } from './routes/dashboard/settings/index'
import { Route as DashboardProcessImagesIndexImport } from './routes/dashboard/process-images/index'
import { Route as DashboardManageIndexImport } from './routes/dashboard/manage/index'
import { Route as DashboardGuidesIndexImport } from './routes/dashboard/guides/index'
import { Route as PathlessLayoutProductReviewsIndexImport } from './routes/_pathlessLayout/product-reviews/index'
import { Route as PathlessLayoutGuidesIndexImport } from './routes/_pathlessLayout/guides/index'
import { Route as PathlessLayoutCalculatorsIndexImport } from './routes/_pathlessLayout/calculators/index'
import { Route as PathlessLayoutBlogsIndexImport } from './routes/_pathlessLayout/blogs/index'
import { Route as PathlessLayoutProductReviewsReviewIdImport } from './routes/_pathlessLayout/product-reviews/$reviewId'
import { Route as PathlessLayoutBlogsIdImport } from './routes/_pathlessLayout/blogs/$id'
import { Route as DashboardManageImagesIndexImport } from './routes/dashboard/manage/images/index'
import { Route as PathlessLayoutGuidesCategoryIndexImport } from './routes/_pathlessLayout/guides/$category/index'
import { Route as PathlessLayoutCalculatorsSolarSystemIndexImport } from './routes/_pathlessLayout/calculators/solar-system/index'
import { Route as PathlessLayoutCalculatorsHomeLoadIndexImport } from './routes/_pathlessLayout/calculators/home-load/index'
import { Route as PathlessLayoutGuidesCategorySlugImport } from './routes/_pathlessLayout/guides/$category/$slug'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutRouteRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const PathlessLayoutIndexRoute = PathlessLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const DashboardSettingsIndexRoute = DashboardSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardProcessImagesIndexRoute =
  DashboardProcessImagesIndexImport.update({
    id: '/process-images/',
    path: '/process-images/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardManageIndexRoute = DashboardManageIndexImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardGuidesIndexRoute = DashboardGuidesIndexImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const PathlessLayoutProductReviewsIndexRoute =
  PathlessLayoutProductReviewsIndexImport.update({
    id: '/product-reviews/',
    path: '/product-reviews/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutGuidesIndexRoute = PathlessLayoutGuidesIndexImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutCalculatorsIndexRoute =
  PathlessLayoutCalculatorsIndexImport.update({
    id: '/calculators/',
    path: '/calculators/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutBlogsIndexRoute = PathlessLayoutBlogsIndexImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutProductReviewsReviewIdRoute =
  PathlessLayoutProductReviewsReviewIdImport.update({
    id: '/product-reviews/$reviewId',
    path: '/product-reviews/$reviewId',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutBlogsIdRoute = PathlessLayoutBlogsIdImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const DashboardManageImagesIndexRoute = DashboardManageImagesIndexImport.update(
  {
    id: '/manage/images/',
    path: '/manage/images/',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
)

const PathlessLayoutGuidesCategoryIndexRoute =
  PathlessLayoutGuidesCategoryIndexImport.update({
    id: '/guides/$category/',
    path: '/guides/$category/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutCalculatorsSolarSystemIndexRoute =
  PathlessLayoutCalculatorsSolarSystemIndexImport.update({
    id: '/calculators/solar-system/',
    path: '/calculators/solar-system/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutCalculatorsHomeLoadIndexRoute =
  PathlessLayoutCalculatorsHomeLoadIndexImport.update({
    id: '/calculators/home-load/',
    path: '/calculators/home-load/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

const PathlessLayoutGuidesCategorySlugRoute =
  PathlessLayoutGuidesCategorySlugImport.update({
    id: '/guides/$category/$slug',
    path: '/guides/$category/$slug',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_pathlessLayout/blogs/$id': {
      id: '/_pathlessLayout/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof PathlessLayoutBlogsIdImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/product-reviews/$reviewId': {
      id: '/_pathlessLayout/product-reviews/$reviewId'
      path: '/product-reviews/$reviewId'
      fullPath: '/product-reviews/$reviewId'
      preLoaderRoute: typeof PathlessLayoutProductReviewsReviewIdImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/blogs/': {
      id: '/_pathlessLayout/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof PathlessLayoutBlogsIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/calculators/': {
      id: '/_pathlessLayout/calculators/'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof PathlessLayoutCalculatorsIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/guides/': {
      id: '/_pathlessLayout/guides/'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof PathlessLayoutGuidesIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/product-reviews/': {
      id: '/_pathlessLayout/product-reviews/'
      path: '/product-reviews'
      fullPath: '/product-reviews'
      preLoaderRoute: typeof PathlessLayoutProductReviewsIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/dashboard/guides/': {
      id: '/dashboard/guides/'
      path: '/guides'
      fullPath: '/dashboard/guides'
      preLoaderRoute: typeof DashboardGuidesIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/manage/': {
      id: '/dashboard/manage/'
      path: '/manage'
      fullPath: '/dashboard/manage'
      preLoaderRoute: typeof DashboardManageIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/process-images/': {
      id: '/dashboard/process-images/'
      path: '/process-images'
      fullPath: '/dashboard/process-images'
      preLoaderRoute: typeof DashboardProcessImagesIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_pathlessLayout/guides/$category/$slug': {
      id: '/_pathlessLayout/guides/$category/$slug'
      path: '/guides/$category/$slug'
      fullPath: '/guides/$category/$slug'
      preLoaderRoute: typeof PathlessLayoutGuidesCategorySlugImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/calculators/home-load/': {
      id: '/_pathlessLayout/calculators/home-load/'
      path: '/calculators/home-load'
      fullPath: '/calculators/home-load'
      preLoaderRoute: typeof PathlessLayoutCalculatorsHomeLoadIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/calculators/solar-system/': {
      id: '/_pathlessLayout/calculators/solar-system/'
      path: '/calculators/solar-system'
      fullPath: '/calculators/solar-system'
      preLoaderRoute: typeof PathlessLayoutCalculatorsSolarSystemIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/guides/$category/': {
      id: '/_pathlessLayout/guides/$category/'
      path: '/guides/$category'
      fullPath: '/guides/$category'
      preLoaderRoute: typeof PathlessLayoutGuidesCategoryIndexImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/dashboard/manage/images/': {
      id: '/dashboard/manage/images/'
      path: '/manage/images'
      fullPath: '/dashboard/manage/images'
      preLoaderRoute: typeof DashboardManageImagesIndexImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutBlogsIdRoute: typeof PathlessLayoutBlogsIdRoute
  PathlessLayoutProductReviewsReviewIdRoute: typeof PathlessLayoutProductReviewsReviewIdRoute
  PathlessLayoutBlogsIndexRoute: typeof PathlessLayoutBlogsIndexRoute
  PathlessLayoutCalculatorsIndexRoute: typeof PathlessLayoutCalculatorsIndexRoute
  PathlessLayoutGuidesIndexRoute: typeof PathlessLayoutGuidesIndexRoute
  PathlessLayoutProductReviewsIndexRoute: typeof PathlessLayoutProductReviewsIndexRoute
  PathlessLayoutGuidesCategorySlugRoute: typeof PathlessLayoutGuidesCategorySlugRoute
  PathlessLayoutCalculatorsHomeLoadIndexRoute: typeof PathlessLayoutCalculatorsHomeLoadIndexRoute
  PathlessLayoutCalculatorsSolarSystemIndexRoute: typeof PathlessLayoutCalculatorsSolarSystemIndexRoute
  PathlessLayoutGuidesCategoryIndexRoute: typeof PathlessLayoutGuidesCategoryIndexRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutBlogsIdRoute: PathlessLayoutBlogsIdRoute,
  PathlessLayoutProductReviewsReviewIdRoute:
    PathlessLayoutProductReviewsReviewIdRoute,
  PathlessLayoutBlogsIndexRoute: PathlessLayoutBlogsIndexRoute,
  PathlessLayoutCalculatorsIndexRoute: PathlessLayoutCalculatorsIndexRoute,
  PathlessLayoutGuidesIndexRoute: PathlessLayoutGuidesIndexRoute,
  PathlessLayoutProductReviewsIndexRoute:
    PathlessLayoutProductReviewsIndexRoute,
  PathlessLayoutGuidesCategorySlugRoute: PathlessLayoutGuidesCategorySlugRoute,
  PathlessLayoutCalculatorsHomeLoadIndexRoute:
    PathlessLayoutCalculatorsHomeLoadIndexRoute,
  PathlessLayoutCalculatorsSolarSystemIndexRoute:
    PathlessLayoutCalculatorsSolarSystemIndexRoute,
  PathlessLayoutGuidesCategoryIndexRoute:
    PathlessLayoutGuidesCategoryIndexRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGuidesIndexRoute: typeof DashboardGuidesIndexRoute
  DashboardManageIndexRoute: typeof DashboardManageIndexRoute
  DashboardProcessImagesIndexRoute: typeof DashboardProcessImagesIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardManageImagesIndexRoute: typeof DashboardManageImagesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGuidesIndexRoute: DashboardGuidesIndexRoute,
  DashboardManageIndexRoute: DashboardManageIndexRoute,
  DashboardProcessImagesIndexRoute: DashboardProcessImagesIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardManageImagesIndexRoute: DashboardManageImagesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PathlessLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof PathlessLayoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/blogs/$id': typeof PathlessLayoutBlogsIdRoute
  '/product-reviews/$reviewId': typeof PathlessLayoutProductReviewsReviewIdRoute
  '/blogs': typeof PathlessLayoutBlogsIndexRoute
  '/calculators': typeof PathlessLayoutCalculatorsIndexRoute
  '/guides': typeof PathlessLayoutGuidesIndexRoute
  '/product-reviews': typeof PathlessLayoutProductReviewsIndexRoute
  '/dashboard/guides': typeof DashboardGuidesIndexRoute
  '/dashboard/manage': typeof DashboardManageIndexRoute
  '/dashboard/process-images': typeof DashboardProcessImagesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/guides/$category/$slug': typeof PathlessLayoutGuidesCategorySlugRoute
  '/calculators/home-load': typeof PathlessLayoutCalculatorsHomeLoadIndexRoute
  '/calculators/solar-system': typeof PathlessLayoutCalculatorsSolarSystemIndexRoute
  '/guides/$category': typeof PathlessLayoutGuidesCategoryIndexRoute
  '/dashboard/manage/images': typeof DashboardManageImagesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof PathlessLayoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/blogs/$id': typeof PathlessLayoutBlogsIdRoute
  '/product-reviews/$reviewId': typeof PathlessLayoutProductReviewsReviewIdRoute
  '/blogs': typeof PathlessLayoutBlogsIndexRoute
  '/calculators': typeof PathlessLayoutCalculatorsIndexRoute
  '/guides': typeof PathlessLayoutGuidesIndexRoute
  '/product-reviews': typeof PathlessLayoutProductReviewsIndexRoute
  '/dashboard/guides': typeof DashboardGuidesIndexRoute
  '/dashboard/manage': typeof DashboardManageIndexRoute
  '/dashboard/process-images': typeof DashboardProcessImagesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/guides/$category/$slug': typeof PathlessLayoutGuidesCategorySlugRoute
  '/calculators/home-load': typeof PathlessLayoutCalculatorsHomeLoadIndexRoute
  '/calculators/solar-system': typeof PathlessLayoutCalculatorsSolarSystemIndexRoute
  '/guides/$category': typeof PathlessLayoutGuidesCategoryIndexRoute
  '/dashboard/manage/images': typeof DashboardManageImagesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_pathlessLayout/blogs/$id': typeof PathlessLayoutBlogsIdRoute
  '/_pathlessLayout/product-reviews/$reviewId': typeof PathlessLayoutProductReviewsReviewIdRoute
  '/_pathlessLayout/blogs/': typeof PathlessLayoutBlogsIndexRoute
  '/_pathlessLayout/calculators/': typeof PathlessLayoutCalculatorsIndexRoute
  '/_pathlessLayout/guides/': typeof PathlessLayoutGuidesIndexRoute
  '/_pathlessLayout/product-reviews/': typeof PathlessLayoutProductReviewsIndexRoute
  '/dashboard/guides/': typeof DashboardGuidesIndexRoute
  '/dashboard/manage/': typeof DashboardManageIndexRoute
  '/dashboard/process-images/': typeof DashboardProcessImagesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_pathlessLayout/guides/$category/$slug': typeof PathlessLayoutGuidesCategorySlugRoute
  '/_pathlessLayout/calculators/home-load/': typeof PathlessLayoutCalculatorsHomeLoadIndexRoute
  '/_pathlessLayout/calculators/solar-system/': typeof PathlessLayoutCalculatorsSolarSystemIndexRoute
  '/_pathlessLayout/guides/$category/': typeof PathlessLayoutGuidesCategoryIndexRoute
  '/dashboard/manage/images/': typeof DashboardManageImagesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/'
    | '/dashboard/'
    | '/blogs/$id'
    | '/product-reviews/$reviewId'
    | '/blogs'
    | '/calculators'
    | '/guides'
    | '/product-reviews'
    | '/dashboard/guides'
    | '/dashboard/manage'
    | '/dashboard/process-images'
    | '/dashboard/settings'
    | '/guides/$category/$slug'
    | '/calculators/home-load'
    | '/calculators/solar-system'
    | '/guides/$category'
    | '/dashboard/manage/images'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/blogs/$id'
    | '/product-reviews/$reviewId'
    | '/blogs'
    | '/calculators'
    | '/guides'
    | '/product-reviews'
    | '/dashboard/guides'
    | '/dashboard/manage'
    | '/dashboard/process-images'
    | '/dashboard/settings'
    | '/guides/$category/$slug'
    | '/calculators/home-load'
    | '/calculators/solar-system'
    | '/guides/$category'
    | '/dashboard/manage/images'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/dashboard'
    | '/_pathlessLayout/'
    | '/dashboard/'
    | '/_pathlessLayout/blogs/$id'
    | '/_pathlessLayout/product-reviews/$reviewId'
    | '/_pathlessLayout/blogs/'
    | '/_pathlessLayout/calculators/'
    | '/_pathlessLayout/guides/'
    | '/_pathlessLayout/product-reviews/'
    | '/dashboard/guides/'
    | '/dashboard/manage/'
    | '/dashboard/process-images/'
    | '/dashboard/settings/'
    | '/_pathlessLayout/guides/$category/$slug'
    | '/_pathlessLayout/calculators/home-load/'
    | '/_pathlessLayout/calculators/solar-system/'
    | '/_pathlessLayout/guides/$category/'
    | '/dashboard/manage/images/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_pathlessLayout",
        "/dashboard"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout/route.tsx",
      "children": [
        "/_pathlessLayout/",
        "/_pathlessLayout/blogs/$id",
        "/_pathlessLayout/product-reviews/$reviewId",
        "/_pathlessLayout/blogs/",
        "/_pathlessLayout/calculators/",
        "/_pathlessLayout/guides/",
        "/_pathlessLayout/product-reviews/",
        "/_pathlessLayout/guides/$category/$slug",
        "/_pathlessLayout/calculators/home-load/",
        "/_pathlessLayout/calculators/solar-system/",
        "/_pathlessLayout/guides/$category/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/",
        "/dashboard/guides/",
        "/dashboard/manage/",
        "/dashboard/process-images/",
        "/dashboard/settings/",
        "/dashboard/manage/images/"
      ]
    },
    "/_pathlessLayout/": {
      "filePath": "_pathlessLayout/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/_pathlessLayout/blogs/$id": {
      "filePath": "_pathlessLayout/blogs/$id.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/product-reviews/$reviewId": {
      "filePath": "_pathlessLayout/product-reviews/$reviewId.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/blogs/": {
      "filePath": "_pathlessLayout/blogs/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/calculators/": {
      "filePath": "_pathlessLayout/calculators/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/guides/": {
      "filePath": "_pathlessLayout/guides/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/product-reviews/": {
      "filePath": "_pathlessLayout/product-reviews/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/dashboard/guides/": {
      "filePath": "dashboard/guides/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/manage/": {
      "filePath": "dashboard/manage/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/process-images/": {
      "filePath": "dashboard/process-images/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings/": {
      "filePath": "dashboard/settings/index.tsx",
      "parent": "/dashboard"
    },
    "/_pathlessLayout/guides/$category/$slug": {
      "filePath": "_pathlessLayout/guides/$category/$slug.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/calculators/home-load/": {
      "filePath": "_pathlessLayout/calculators/home-load/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/calculators/solar-system/": {
      "filePath": "_pathlessLayout/calculators/solar-system/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/guides/$category/": {
      "filePath": "_pathlessLayout/guides/$category/index.tsx",
      "parent": "/_pathlessLayout"
    },
    "/dashboard/manage/images/": {
      "filePath": "dashboard/manage/images/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
